name: Slim LLVM
on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: "Repository to checkout"
        required: true
        default: MondayNitro/android_kernel_motorola_sm6375
      source_branch:
        description: "Branch to checkout"
        required: true
        default: lineage-23.0
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build for fogos"
    steps:
      - name: Checkout source
        uses: actions/checkout@v7
        with:
          repository: ${{ github.event.inputs.source_repo }}
          ref: ${{ github.event.inputs.source_branch }}
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 1

      - name: Set Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Kolkata"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            bison flex libssl-dev libarchive-tools \
            bc libelf-dev dwarves curl

      - name: Restore LLVM toolchain from cache
        uses: actions/cache/restore@v6
        with:
          path: toolchain
          key: llvm
          fail-on-cache-miss: true

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 30

      - name: Build kernel
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload kernel zip
        uses: actions/upload-artifact@v7
        with:
          name: kernel-${{ github.run_number }}
          path: AnyKernel3/*

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: build-log-${{ github.run_number }}
          path: |
            build.log
            kernel_config
